const questions = () => [{
    answer: 'a',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'b',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'c',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'd',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'e',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'f',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'g',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'h',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'i',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'j',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'k',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'l',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'm',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'n',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'o',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'p',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'q',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'r',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 's',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 't',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'u',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'v',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'w',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'x',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'y',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    answer: 'z',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
];

export default questions;
