const questions = [{
    question: '1+1',
    answer: '2',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    question: '1+2',
    answer: '3',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    question: '1+3',
    answer: '4',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    question: '1+4',
    answer: '5',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    question: '1+5',
    answer: '6',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
  {
    question: '1+6',
    answer: '7',
    quality: 0,
    easeFactor: 2.5,
    repetitions: 0,
    interval: 0,
  },
];

export default questions;
